repos:
  - repo: local
    hooks:
      - id: prospector
        name: prospector
        language: system
        entry: prospector
        args:
          - "--with-tool=mypy"
          - "--with-tool=pyroma"

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: ruff check
        files: \.py$
      - id: ruff-format
        name: ruff-format
        language: system
        entry: ruff format
        args:
          - "--check"
          - "--diff"
        files: \.py$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
