repos:
  - repo: local
    hooks:
      - id: prospector
        name: prospector
        language: system
        entry: prospector
        additional_dependencies:
          - ".[with_mypy,with_pyroma]"
        args:
          - "--with-tool=mypy"
          - "--with-tool=pyroma"

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: ruff check
      - id: ruff-format
        name: ruff-format
        language: system
        entry: ruff format
        args:
          - "--check"
          - "--diff"

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
