strictness: veryhigh
autodetect: false
inherits:
    - default
ignore-paths:
    - build
    - dist
ignore-patterns:
    - __pycache__

max-line-length: 120

dodgy:
    run: true

pylint:
    run: true

pyroma:
    run: true

mypy:
    run: true
    options:
        ignore-missing-imports: true

mccabe:
    run: false

pycodestyle:
    run: false

pyflakes:
    run: false
