src = [
    "src",
    "tests",
]
target-version = "py310"
line-length = 120
indent-width = 4
output-format = "full"

[lint.per-file-ignores]
"**/{tests}/*" = [
    "S603",  # NOTE: Disable for testing.
    "S607",  # NOTE: Disable for testing.
    "S404",  # NOTE: Disable for testing.
]

[lint]
select = [
    "ALL"
]
ignore = [
    "ANN101",  # mypy infer the type of self automatically.
    "D",       # TODO: Remove this line.
    "FBT001",  # NOTE: Ignored to overwrite third party package methods.
    "CPY001",  # NOTE: Ignore copyright notice.
]

fixable = [
    "ALL"
]
unfixable = []

[lint.isort]
lines-after-imports = 2

[lint.flake8-builtins]
builtins-ignorelist = [
    "id",
]

[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "double"

[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 10
