src = [
    "src",
    "tests",
]
target-version = "py310"
line-length = 120
indent-width = 4
output-format = "full"

[lint.per-file-ignores]
"**/{tests}/*" = [
    "S603",  # NOTE: Disable for testing.
    "S607",  # NOTE: Disable for testing.
    "S404",  # NOTE: Disable for testing.
]
"cplayer/__main__.py" = [
    "E402",  # NOTE: Already tested by prospector:pylint.
]

[lint]
select = [
    "ALL"
]
ignore = [
    "ANN101",  # NOTE: mypy infer the type of self automatically.
    "D",       # TODO: Remove this line.
    "FBT001",  # NOTE: Ignored to overwrite third party package methods.
    "CPY001",  # NOTE: Ignore copyright notice.
    "COM812",  # NOTE: May cause conflicts when used with the ruff formatter.
    "ISC001",  # NOTE: May cause conflicts when used with the ruff formatter.
]

fixable = [
    "ALL"
]
unfixable = []

[lint.isort]
lines-after-imports = 2

[lint.flake8-builtins]
builtins-ignorelist = [
    "id",
]

[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"

[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 10

[format]
quote-style = "single"
